### ISSUE TITLE
make a mirror for manjaro but exclude any package that is already exists in manjaro's official repositories to prevent conflicts

### ISSUE THREAD

**Issue by barfin** [PedroHLC/chaotic-aur#66]

**Comment by librewish** [comment]
well those that already exist in manjaro repo are outdated ones.
and nothing conflicts with manjaro.
but yes.
this repo cant be used with manjaro stable branch.
as most package libs are outdated in manjaro stable.

for this to work we will need to recompile every package against manjaro repo.

but anyway @PedroHLC 
can make the decision.

**Comment by PedroHLC** [comment]
Hi @barfin,

In `/etc/pacman.conf` don't put `[chaotic-aur]` before Manjaro's repositories. Put it after.
This way majaro's package will always be preferred instead of ours. And if you need to enforce the installation you'll be able to do using pacman this way: `pacman -Syu chaotic-aur/mhwd`.

Please let me know if this answer satisfies your use-case.

**Comment by barfin** [comment]
> Hi @barfin,
> 
> In `/etc/pacman.conf` don't put `[chaotic-aur]` before Manjaro's repositories. Put it after.
> This way majaro's package will always be preferred instead of ours. And if you need to enforce the installation you'll be able to do using pacman this way: `pacman -Syu chaotic-aur/mhwd`.
> 
> Please let me know if this answer satisfies your use-case.

thanks i used it for game emulators and nothing has gone wrong yet
